### ISSUE TITLE
parse_m3u这个方法在线解析参数写错了

### ISSUE THREAD

**Issue by biancangming** [pawanpaudel93/m3u_parser#1]
![image](https://user-images.githubusercontent.com/42108047/101624627-273ef280-3a55-11eb-88aa-f7c7e06e1eef.png)
这块应该是path

**Comment by pawanpaudel93** [comment]
@biancangming path can be url or file path. path is checked if it is url or not else it will be file path. urpparse(path).scheme !="" or re.search(self.__url_regex, path) checks if it is a url else it will be a file path. Did you have any problem ??

**Comment by biancangming** [comment]
你的源码将path写成url，导致此处报错，这是我修改后的结果 ^0^

**Comment by pawanpaudel93** [comment]
@biancangming Thank you for pointing it out. I didn't get what you meant before and now another issue was raised and I understand what you were trying to say before... Thanks a lot.
