### ISSUE TITLE
Avoid generating empty JSON keys

### ISSUE THREAD

**Issue by dineiar** [pawanpaudel93/m3u_parser#10]
When using `to_file` or `get_json` functions, m3u_parser generates all the keys, even the ones that were not present in the parsed M3U. For example, consider the following sample M3U input file (`sample.m3u`):
```m3u
#EXTM3U
#EXTINF:-1 tvg-id="google" tvg-name="Google" group-title="Google Group", Google
http://www.google.com/
```
Using the following code:
```python
parser = M3uParser()
parser.parse_m3u("sample.m3u")
parser.to_file("out.json")
```
The output file (`out.json`) looks like:
```json
[
    {
        "name": " Google",
        "logo": "",
        "url": "http://www.google.com/",
        "category": "Google Group",
        "language": {
            "code": "",
            "name": ""
        },
        "country": {
            "code": "",
            "name": ""
        },
        "tvg": {
            "id": "google",
            "name": "Google",
            "url": ""
        },
        "status": "GOOD"
    }
]
```

It doesn't make sense to output fields like "language" and "country", since they were not provided in the source M3U file.

**Comment by pawanpaudel93** [comment]
@dineiar My motive was to create a uniform structure for all the m3u files. What if some contain one information and some other don't inside a m3u file? Do you have any suggestions ??

**Comment by dineiar** [comment]
I think it is better to only generate the keys that were present at the original M3U file. JSON allows for this flexibility, it does not enforces a schema for all items on a list. When processing a JSON structure, it is expected that some keys may be missing if they do not have a value.

**Comment by pawanpaudel93** [comment]
@dineiar do you think its better now ??

**Comment by dineiar** [comment]
@pawanpaudel93, yes, it is!

I continued your work and added this same treatment for the other keys, such as `tvg-` ones, `category`, and so on. Check my PR #11.
