### ISSUE TITLE
Doesn't see the value of the URL to the local address: http://192.168.0.3/m3u/Other.m3u

### ISSUE THREAD

**Issue by r35p3ct** [pawanpaudel93/m3u_parser#16]
Doesn't see the value of the URL to the local address:
```
#EXTINF:0 ,Other
http://192.168.0.3/m3u/Other.m3u
```

**Comment by r35p3ct** [comment]
and `acestream://879adbc189269d07502688abdfe33283962142ff`

**Comment by pawanpaudel93** [comment]
@r35p3ct Can you install the latest version and check if everything works correctly.
