### ISSUE TITLE
Write the parsed list to M3U format

### ISSUE THREAD

**Issue by dineiar** [pawanpaudel93/m3u_parser#7]
The package currently does not provide a way to write parsed entries back to m3u format, am I right?

I think it would be nice to have the option to save `streams_info` in m3u format after applying some filters to the parsed list. Currently, `to_file` function only offers the option to save as json or csv format.

**Comment by pawanpaudel93** [comment]
@dineiar Yes the package only supports parsed m3u to CSV and JSON and not back to m3u format currently. Yes, that's a great idea to put the parsed m3u back to its original format. Thanks for your suggestion.

**Comment by dineiar** [comment]
Great. I'll try to provide a PR in the next few days with this.

**Comment by pawanpaudel93** [comment]
@dineiar I have added support for saving back to m3u format.. Please check and give feedback...

**Comment by dineiar** [comment]
Hey @pawanpaudel93, thanks for the quick answer. It works! However, I'm working with somewhat big M3U files and generating them was taking some tome. I tried to improve your code in the PR #11, please check it out.

**Comment by pawanpaudel93** [comment]
@dineiar Thanks for your PR #11.
